SplineFontDB: 3.2
FontName: Grascii
FullName: Grascii
FamilyName: Grascii
Weight: Regular
Copyright: Copyright (c) 2025, Grascii: Language and Tools for Gregg Shorthand
UComments: "2025-5-9: Created with FontForge (http://fontforge.org)"
Version: 001.000
StrokeWidth: 10
ItalicAngle: 0
UnderlinePosition: -100
UnderlineWidth: 50
Ascent: 850
Descent: 150
InvalidEm: 0
LayerCount: 2
Layer: 0 0 "Back" 1
Layer: 1 0 "Fore" 0
StrokedFont: 1
XUID: [1021 822 1269808884 1022652]
FSType: 0
OS2Version: 0
OS2_WeightWidthSlopeOnly: 0
OS2_UseTypoMetrics: 1
CreationTime: 1746848514
ModificationTime: 1747542039
PfmFamily: 17
TTFWeight: 700
TTFWidth: 5
LineGap: 90
VLineGap: 0
OS2TypoAscent: 0
OS2TypoAOffset: 1
OS2TypoDescent: 0
OS2TypoDOffset: 1
OS2TypoLinegap: 90
OS2WinAscent: 0
OS2WinAOffset: 1
OS2WinDescent: 0
OS2WinDOffset: 1
HheadAscent: 0
HheadAOffset: 1
HheadDescent: 0
HheadDOffset: 1
OS2Vendor: 'PfEd'
Lookup: 4 0 0 "Multichar strokes" { "ch sh th ng nk"  } ['rlig' ('DFLT' <'dflt' > 'latn' <'dflt' > ) ]
Lookup: 6 0 0 "Vowel Joinings" { "Vowel Before Overrides"  "Vowel Before"  "Vowel After Overrides"  "Vowel After"  } ['rclt' ('DFLT' <'dflt' > 'latn' <'dflt' > ) ]
Lookup: 1 0 0 "Before ch" { "Before ch"  } []
Lookup: 1 0 0 "Before f" { "Before f"  } []
Lookup: 1 0 0 "Before k" { "Before k"  } []
Lookup: 1 0 0 "Before l" { "Before l"  } []
Lookup: 1 0 0 "Before n" { "Before n"  } []
Lookup: 1 0 0 "Before ng" { "Before ng"  } []
Lookup: 1 0 0 "Before p" { "Before p"  } []
Lookup: 1 0 0 "Before r" { "Before r"  } []
Lookup: 1 0 0 "Before t" { "Before t"  } []
Lookup: 1 0 0 "Before th" { "Before th"  } []
Lookup: 1 0 0 "Before v" { "Before v"  } []
Lookup: 1 0 0 "After b" { "After b"  } []
Lookup: 1 0 0 "After ch" { "After ch"  } []
Lookup: 1 0 0 "After f" { "After f"  } []
Lookup: 1 0 0 "After k" { "After k"  } []
Lookup: 1 0 0 "After n" { "After n"  } []
Lookup: 1 0 0 "After ng" { "After ng"  } []
Lookup: 1 0 0 "After p" { "After p"  } []
Lookup: 1 0 0 "After r" { "After r"  } []
Lookup: 1 0 0 "After t" { "After t"  } []
Lookup: 1 0 0 "After th" { "After th"  } []
Lookup: 264 0 0 "Line of Writing" { "Starts with a"  } [' RQD' ('DFLT' <'dflt' > 'latn' <'dflt' > ) ]
Lookup: 259 0 0 "Cursive Attachment" { "Join"  } ['curs' ('DFLT' <'dflt' > 'latn' <'dflt' > ) ]
Lookup: 257 0 0 "Position Before b" { "Position Before b"  } []
Lookup: 257 0 0 "Position Before ch" { "Position Before ch"  } []
Lookup: 257 0 0 "Position Before d" { "Position Before d"  } []
Lookup: 257 0 0 "Position Before f" { "Position Before f"  } []
Lookup: 257 0 0 "Position Before g" { "Position Before g"  } []
Lookup: 257 0 0 "Position Before j" { "Position Before j"  } []
Lookup: 257 0 0 "Position Before k" { "Position Before k"  } []
Lookup: 257 0 0 "Position Before l" { "Position Before l"  } []
Lookup: 257 0 0 "Position Before m" { "Position Before m"  } []
Lookup: 257 0 0 "Position Before n" { "Position Before n"  } []
Lookup: 257 0 0 "Position Before ng" { "Position Before ng"  } []
Lookup: 257 0 0 "Position Before nk" { "Position Before nk"  } []
Lookup: 257 0 0 "Position Before p" { "Position Before p"  } []
Lookup: 257 0 0 "Position Before r" { "Position Before r"  } []
Lookup: 257 0 0 "Position Before sh" { "Position Before sh"  } []
Lookup: 257 0 0 "Position Before t" { "Position Before t"  } []
Lookup: 257 0 0 "Position Before th" { "Position Before th"  } []
Lookup: 257 0 0 "Position Before v" { "Position Before v"  } []
MarkAttachClasses: 1
DEI: 91125
ChainSub2: glyph "Vowel After Overrides" 0 0 0 1
 String: 1 a
 BString: 1 b
 FString: 0 
 1
  SeqLookup: 0 "After b"
EndFPST
ChainSub2: class "Vowel After" 11 11 11 9
  Class: 1 a
  Class: 7 sh ch j
  Class: 3 f v
  Class: 3 k g
  Class: 3 n m
  Class: 3 p b
  Class: 3 r l
  Class: 3 t d
  Class: 2 th
  Class: 5 ng nk
  BClass: 1 a
  BClass: 7 sh ch j
  BClass: 3 f v
  BClass: 3 k g
  BClass: 3 n m
  BClass: 3 p b
  BClass: 3 r l
  BClass: 3 t d
  BClass: 2 th
  BClass: 5 ng nk
  FClass: 1 a
  FClass: 7 sh ch j
  FClass: 3 f v
  FClass: 3 k g
  FClass: 3 n m
  FClass: 3 p b
  FClass: 3 r l
  FClass: 3 t d
  FClass: 2 th
  FClass: 5 ng nk
 1 1 0
  ClsList: 1
  BClsList: 2
  FClsList:
 1
  SeqLookup: 0 "After ch"
 1 1 0
  ClsList: 1
  BClsList: 3
  FClsList:
 1
  SeqLookup: 0 "After f"
 1 1 0
  ClsList: 1
  BClsList: 4
  FClsList:
 1
  SeqLookup: 0 "After k"
 1 1 0
  ClsList: 1
  BClsList: 5
  FClsList:
 1
  SeqLookup: 0 "After n"
 1 1 0
  ClsList: 1
  BClsList: 6
  FClsList:
 1
  SeqLookup: 0 "After p"
 1 1 0
  ClsList: 1
  BClsList: 7
  FClsList:
 1
  SeqLookup: 0 "After r"
 1 1 0
  ClsList: 1
  BClsList: 8
  FClsList:
 1
  SeqLookup: 0 "After t"
 1 1 0
  ClsList: 1
  BClsList: 9
  FClsList:
 1
  SeqLookup: 0 "After th"
 1 1 0
  ClsList: 1
  BClsList: 10
  FClsList:
 1
  SeqLookup: 0 "After ng"
  ClassNames: "All_Others" "a" "ch" "f" "k" "n" "p" "r" "t" "th" "ng"
  BClassNames: "All_Others" "a" "ch" "f" "k" "n" "p" "r" "t" "th" "ng"
  FClassNames: "All_Others" "a" "ch" "f" "k" "n" "p" "r" "t" "th" "ng"
EndFPST
ChainPos2: class "Starts with a" 12 12 19 17
  Class: 5 a.ach
  Class: 4 a.af
  Class: 4 a.ak
  Class: 4 a.al
  Class: 4 a.an
  Class: 5 a.ang
  Class: 4 a.ap
  Class: 4 a.ar
  Class: 4 a.at
  Class: 5 a.ath
  Class: 4 a.av
  BClass: 5 a.ach
  BClass: 4 a.af
  BClass: 4 a.ak
  BClass: 4 a.al
  BClass: 4 a.an
  BClass: 5 a.ang
  BClass: 4 a.ap
  BClass: 4 a.ar
  BClass: 4 a.at
  BClass: 5 a.ath
  BClass: 4 a.av
  FClass: 1 b
  FClass: 2 ch
  FClass: 1 d
  FClass: 1 f
  FClass: 1 g
  FClass: 1 j
  FClass: 1 k
  FClass: 1 l
  FClass: 1 m
  FClass: 1 n
  FClass: 2 ng
  FClass: 2 nk
  FClass: 1 p
  FClass: 1 r
  FClass: 2 sh
  FClass: 1 t
  FClass: 2 th
  FClass: 1 v
 1 0 1
  ClsList: 7
  BClsList:
  FClsList: 1
 1
  SeqLookup: 0 "Position Before b"
 1 0 1
  ClsList: 1
  BClsList:
  FClsList: 2
 1
  SeqLookup: 0 "Position Before ch"
 1 0 1
  ClsList: 9
  BClsList:
  FClsList: 3
 1
  SeqLookup: 0 "Position Before d"
 1 0 1
  ClsList: 2
  BClsList:
  FClsList: 4
 1
  SeqLookup: 0 "Position Before f"
 1 0 1
  ClsList: 3
  BClsList:
  FClsList: 5
 1
  SeqLookup: 0 "Position Before g"
 1 0 1
  ClsList: 1
  BClsList:
  FClsList: 6
 1
  SeqLookup: 0 "Position Before j"
 1 0 1
  ClsList: 3
  BClsList:
  FClsList: 7
 1
  SeqLookup: 0 "Position Before k"
 1 0 1
  ClsList: 4
  BClsList:
  FClsList: 8
 1
  SeqLookup: 0 "Position Before l"
 1 0 1
  ClsList: 5
  BClsList:
  FClsList: 9
 1
  SeqLookup: 0 "Position Before m"
 1 0 1
  ClsList: 5
  BClsList:
  FClsList: 10
 1
  SeqLookup: 0 "Position Before n"
 1 0 1
  ClsList: 6
  BClsList:
  FClsList: 11
 1
  SeqLookup: 0 "Position Before ng"
 1 0 1
  ClsList: 6
  BClsList:
  FClsList: 12
 1
  SeqLookup: 0 "Position Before nk"
 1 0 1
  ClsList: 7
  BClsList:
  FClsList: 13
 1
  SeqLookup: 0 "Position Before p"
 1 0 1
  ClsList: 8
  BClsList:
  FClsList: 14
 1
  SeqLookup: 0 "Position Before r"
 1 0 1
  ClsList: 1
  BClsList:
  FClsList: 15
 1
  SeqLookup: 0 "Position Before sh"
 1 0 1
  ClsList: 9
  BClsList:
  FClsList: 16
 1
  SeqLookup: 0 "Position Before t"
 1 0 1
  ClsList: 11
  BClsList:
  FClsList: 18
 1
  SeqLookup: 0 "Position Before v"
  ClassNames: "All_Others" "a.ach" "a.af" "a.ak" "a.al" "a.an" "a.ang" "a.ap" "a.ar" "a.at" "a.ath" "a.av"
  BClassNames: "All_Others" "a.ach" "a.af" "a.ak" "a.al" "a.an" "a.ang" "a.ap" "a.ar" "a.at" "a.ath" "a.av"
  FClassNames: "All_Others" "b" "ch" "d" "f" "g" "j" "k" "l" "m" "n" "ng" "nk" "p" "r" "sh" "t" "th" "v"
EndFPST
ChainSub2: glyph "Vowel Before Overrides" 0 0 0 2
 String: 1 a
 BString: 0 
 FString: 1 l
 1
  SeqLookup: 0 "Before l"
 String: 1 a
 BString: 0 
 FString: 1 v
 1
  SeqLookup: 0 "Before v"
EndFPST
ChainSub2: class "Vowel Before" 11 1 11 9
  Class: 1 a
  Class: 7 sh ch j
  Class: 3 f v
  Class: 3 k g
  Class: 3 n m
  Class: 3 p b
  Class: 3 r l
  Class: 3 t d
  Class: 2 th
  Class: 5 ng nk
  FClass: 1 a
  FClass: 7 sh ch j
  FClass: 3 f v
  FClass: 3 k g
  FClass: 3 n m
  FClass: 3 p b
  FClass: 3 r l
  FClass: 3 t d
  FClass: 2 th
  FClass: 5 ng nk
 1 0 1
  ClsList: 1
  BClsList:
  FClsList: 2
 1
  SeqLookup: 0 "Before ch"
 1 0 1
  ClsList: 1
  BClsList:
  FClsList: 3
 1
  SeqLookup: 0 "Before f"
 1 0 1
  ClsList: 1
  BClsList:
  FClsList: 4
 1
  SeqLookup: 0 "Before k"
 1 0 1
  ClsList: 1
  BClsList:
  FClsList: 5
 1
  SeqLookup: 0 "Before n"
 1 0 1
  ClsList: 1
  BClsList:
  FClsList: 6
 1
  SeqLookup: 0 "Before p"
 1 0 1
  ClsList: 1
  BClsList:
  FClsList: 7
 1
  SeqLookup: 0 "Before r"
 1 0 1
  ClsList: 1
  BClsList:
  FClsList: 8
 1
  SeqLookup: 0 "Before t"
 1 0 1
  ClsList: 1
  BClsList:
  FClsList: 9
 1
  SeqLookup: 0 "Before th"
 1 0 1
  ClsList: 1
  BClsList:
  FClsList: 10
 1
  SeqLookup: 0 "Before ng"
  ClassNames: "All_Others" "a" "ch" "f" "k" "n" "p" "r" "t" "th" "ng"
  BClassNames: "All_Others"
  FClassNames: "All_Others" "a" "ch" "f" "k" "n" "p" "r" "t" "th" "ng"
EndFPST
Encoding: ISO8859-1
UnicodeInterp: none
NameList: AGL For New Fonts
DisplaySize: -72
AntiAlias: 1
FitToEm: 0
WinInfo: 104 26 10
BeginPrivate: 0
EndPrivate
TeXData: 1 0 0 346030 173015 115343 0 1048576 115343 783286 444596 497025 792723 393216 433062 380633 303038 157286 324010 404750 52429 2506097 1059062 262144
AnchorClass2: "Join" "Join"
EndSplineFont
