SplineFontDB: 3.2
FontName: Grascii
FullName: Grascii
FamilyName: Grascii
Weight: Regular
Copyright: Copyright (c) 2025, Grascii: Language and Tools for Gregg Shorthand
UComments: "2025-5-9: Created with FontForge (http://fontforge.org)"
Version: 001.000
StrokeWidth: 10
ItalicAngle: 0
UnderlinePosition: -100
UnderlineWidth: 50
Ascent: 850
Descent: 150
InvalidEm: 0
LayerCount: 2
Layer: 0 0 "Back" 1
Layer: 1 0 "Fore" 0
StrokedFont: 1
XUID: [1021 822 1269808884 1022652]
FSType: 0
OS2Version: 0
OS2_WeightWidthSlopeOnly: 0
OS2_UseTypoMetrics: 1
CreationTime: 1746848514
ModificationTime: 1747978596
PfmFamily: 17
TTFWeight: 700
TTFWidth: 5
LineGap: 90
VLineGap: 0
OS2TypoAscent: 0
OS2TypoAOffset: 1
OS2TypoDescent: 0
OS2TypoDOffset: 1
OS2TypoLinegap: 90
OS2WinAscent: 0
OS2WinAOffset: 1
OS2WinDescent: 0
OS2WinDOffset: 1
HheadAscent: 0
HheadAOffset: 1
HheadDescent: 0
HheadDOffset: 1
OS2Vendor: 'PfEd'
Lookup: 4 0 0 "Multichar strokes" { "ch sh th ng nk"  } ['rlig' ('DFLT' <'dflt' > 'latn' <'dflt' > ) ]
Lookup: 4 0 0 "Annotated Directions" { "Annotated Directions"  } ['rlig' ('DFLT' <'dflt' > 'latn' <'dflt' > ) ]
Lookup: 6 0 0 "Directions" { "s Direction"  "th Direction"  } ['rclt' ('DFLT' <'dflt' > 'latn' <'dflt' > ) ]
Lookup: 6 0 0 "Consonant Joinings" { "p Joinings"  } ['rclt' ('DFLT' <'dflt' > 'latn' <'dflt' > ) ]
Lookup: 6 0 1 "Vowel Between" { "Between k *"  "Between r *"  "Between n *"  "Between t *"  "Between p *"  "Between f *"  "Between ch *"  "Between ng *"  "Between tn *"  "Between nt *"  } ['rclt' ('latn' <'dflt' > ) ]
Lookup: 6 0 0 "Vowel Before/After" { "Vowel Before Overrides"  "Vowel Before"  "Vowel After Overrides"  "Vowel After"  } ['rclt' ('DFLT' <'dflt' > 'latn' <'dflt' > ) ]
Lookup: 1 0 0 "Cut Consonant" { "Cut Consonant" ("cut") } []
Lookup: 1 0 0 "Right s" { "Right s"  } []
Lookup: 1 0 0 "Left s" { "Left s"  } []
Lookup: 1 0 0 "Over th" { "Over th"  } []
Lookup: 1 0 0 "Under th" { "Under th"  } []
Lookup: 1 0 0 "Before ch" { "Before ch"  } []
Lookup: 1 0 0 "Before f" { "Before f"  } []
Lookup: 1 0 0 "Before k" { "Before k"  } []
Lookup: 1 0 0 "Before l" { "Before l"  } []
Lookup: 1 0 0 "Before n" { "Before n"  } []
Lookup: 1 0 0 "Before ng" { "Before ng"  } []
Lookup: 1 0 0 "Before nt" { "Before nt"  } []
Lookup: 1 0 0 "Before p" { "Before p"  } []
Lookup: 1 0 0 "Before r" { "Before r"  } []
Lookup: 1 0 0 "Before t" { "Before t"  } []
Lookup: 1 0 0 "Before s.right" { "Before s.right"  } []
Lookup: 1 0 0 "Before tn" { "Before tn"  } []
Lookup: 1 0 0 "Before v" { "Before v"  } []
Lookup: 1 0 0 "After b" { "After b"  } []
Lookup: 1 0 0 "After ch" { "After ch"  } []
Lookup: 1 0 0 "After f" { "After f"  } []
Lookup: 1 0 0 "After k" { "After k"  } []
Lookup: 1 0 0 "After n" { "After n"  } []
Lookup: 1 0 0 "After ng" { "After ng"  } []
Lookup: 1 0 0 "After nt" { "After nt"  } []
Lookup: 1 0 0 "After p" { "After p"  } []
Lookup: 1 0 0 "After r" { "After r"  } []
Lookup: 1 0 0 "After s.right" { "After s.right"  } []
Lookup: 1 0 0 "After s.left" { "After s.left"  } []
Lookup: 1 0 0 "After t" { "After t"  } []
Lookup: 1 0 0 "After tn" { "After tn"  } []
Lookup: 1 0 0 "Between k k" { "Between k k"  } []
Lookup: 1 0 0 "Between k r" { "Between k r"  } []
Lookup: 1 0 0 "Between k n" { "Between k n"  } []
Lookup: 1 0 0 "Between k t" { "Between k t"  } []
Lookup: 1 0 0 "Between k p" { "Between k p"  } []
Lookup: 1 0 0 "Between k f" { "Between k f"  } []
Lookup: 1 0 0 "Between k ch" { "Between k ch"  } []
Lookup: 1 0 0 "Between k ng" { "Between k ng"  } []
Lookup: 1 0 0 "Between k tn" { "Between k tn"  } []
Lookup: 1 0 0 "Between k nt" { "Between k nt"  } []
Lookup: 1 0 0 "Between r k" { "Between r k"  } []
Lookup: 1 0 0 "Between r r" { "Between r r"  } []
Lookup: 1 0 0 "Between r n" { "Between r n"  } []
Lookup: 1 0 0 "Between r t" { "Between r t"  } []
Lookup: 1 0 0 "Between r p" { "Between r p"  } []
Lookup: 1 0 0 "Between r f" { "Between r f"  } []
Lookup: 1 0 0 "Between r ch" { "Between r ch"  } []
Lookup: 1 0 0 "Between r ng" { "Between r ng"  } []
Lookup: 1 0 0 "Between r tn" { "Between r tn"  } []
Lookup: 1 0 0 "Between r nt" { "Between r nt"  } []
Lookup: 1 0 0 "Between n k" { "Between n k"  } []
Lookup: 1 0 0 "Between n r" { "Between n r"  } []
Lookup: 1 0 0 "Between n n" { "Between n n"  } []
Lookup: 1 0 0 "Between n t" { "Between n t"  } []
Lookup: 1 0 0 "Between n p" { "Between n p"  } []
Lookup: 1 0 0 "Between n f" { "Between n f"  } []
Lookup: 1 0 0 "Between n ch" { "Between n ch"  } []
Lookup: 1 0 0 "Between n ng" { "Between n ng"  } []
Lookup: 1 0 0 "Between n tn" { "Between n tn"  } []
Lookup: 1 0 0 "Between n nt" { "Between n nt"  } []
Lookup: 1 0 0 "Between t k" { "Between t k"  } []
Lookup: 1 0 0 "Between t r" { "Between t r"  } []
Lookup: 1 0 0 "Between t n" { "Between t n"  } []
Lookup: 1 0 0 "Between t t" { "Between t t"  } []
Lookup: 1 0 0 "Between t p" { "Between t p"  } []
Lookup: 1 0 0 "Between t f" { "Between t f"  } []
Lookup: 1 0 0 "Between t ch" { "Between t ch"  } []
Lookup: 1 0 0 "Between t ng" { "Between t ng"  } []
Lookup: 1 0 0 "Between t tn" { "Between t tn"  } []
Lookup: 1 0 0 "Between t nt" { "Between t nt"  } []
Lookup: 1 0 0 "Between p k" { "Between p k"  } []
Lookup: 1 0 0 "Between p r" { "Between p r"  } []
Lookup: 1 0 0 "Between p n" { "Between p n"  } []
Lookup: 1 0 0 "Between p t" { "Between p t"  } []
Lookup: 1 0 0 "Between p p" { "Between p p"  } []
Lookup: 1 0 0 "Between p f" { "Between p f"  } []
Lookup: 1 0 0 "Between p ch" { "Between p ch"  } []
Lookup: 1 0 0 "Between p ng" { "Between p ng"  } []
Lookup: 1 0 0 "Between p tn" { "Between p tn"  } []
Lookup: 1 0 0 "Between p nt" { "Between p nt"  } []
Lookup: 1 0 0 "Between f k" { "Between f k"  } []
Lookup: 1 0 0 "Between f r" { "Between f r"  } []
Lookup: 1 0 0 "Between f n" { "Between f n"  } []
Lookup: 1 0 0 "Between f t" { "Between f t"  } []
Lookup: 1 0 0 "Between f p" { "Between f p"  } []
Lookup: 1 0 0 "Between f f" { "Between f f"  } []
Lookup: 1 0 0 "Between f ch" { "Between f ch"  } []
Lookup: 1 0 0 "Between f ng" { "Between f ng"  } []
Lookup: 1 0 0 "Between f tn" { "Between f tn"  } []
Lookup: 1 0 0 "Between f nt" { "Between f nt"  } []
Lookup: 1 0 0 "Between ch k" { "Between ch k"  } []
Lookup: 1 0 0 "Between ch r" { "Between ch r"  } []
Lookup: 1 0 0 "Between ch n" { "Between ch n"  } []
Lookup: 1 0 0 "Between ch t" { "Between ch t"  } []
Lookup: 1 0 0 "Between ch p" { "Between ch p"  } []
Lookup: 1 0 0 "Between ch f" { "Between ch f"  } []
Lookup: 1 0 0 "Between ch ch" { "Between ch ch"  } []
Lookup: 1 0 0 "Between ch ng" { "Between ch ng"  } []
Lookup: 1 0 0 "Between ch tn" { "Between ch tn"  } []
Lookup: 1 0 0 "Between ch nt" { "Between ch nt"  } []
Lookup: 1 0 0 "Between ng k" { "Between ng k"  } []
Lookup: 1 0 0 "Between ng r" { "Between ng r"  } []
Lookup: 1 0 0 "Between ng n" { "Between ng n"  } []
Lookup: 1 0 0 "Between ng t" { "Between ng t"  } []
Lookup: 1 0 0 "Between ng p" { "Between ng p"  } []
Lookup: 1 0 0 "Between ng f" { "Between ng f"  } []
Lookup: 1 0 0 "Between ng ch" { "Between ng ch"  } []
Lookup: 1 0 0 "Between ng ng" { "Between ng ng"  } []
Lookup: 1 0 0 "Between ng tn" { "Between ng tn"  } []
Lookup: 1 0 0 "Between ng nt" { "Between ng nt"  } []
Lookup: 1 0 0 "Between tn k" { "Between tn k"  } []
Lookup: 1 0 0 "Between tn r" { "Between tn r"  } []
Lookup: 1 0 0 "Between tn n" { "Between tn n"  } []
Lookup: 1 0 0 "Between tn t" { "Between tn t"  } []
Lookup: 1 0 0 "Between tn p" { "Between tn p"  } []
Lookup: 1 0 0 "Between tn f" { "Between tn f"  } []
Lookup: 1 0 0 "Between tn ch" { "Between tn ch"  } []
Lookup: 1 0 0 "Between tn ng" { "Between tn ng"  } []
Lookup: 1 0 0 "Between tn tn" { "Between tn tn"  } []
Lookup: 1 0 0 "Between tn nt" { "Between tn nt"  } []
Lookup: 1 0 0 "Between nt k" { "Between nt k"  } []
Lookup: 1 0 0 "Between nt r" { "Between nt r"  } []
Lookup: 1 0 0 "Between nt n" { "Between nt n"  } []
Lookup: 1 0 0 "Between nt t" { "Between nt t"  } []
Lookup: 1 0 0 "Between nt p" { "Between nt p"  } []
Lookup: 1 0 0 "Between nt f" { "Between nt f"  } []
Lookup: 1 0 0 "Between nt ch" { "Between nt ch"  } []
Lookup: 1 0 0 "Between nt ng" { "Between nt ng"  } []
Lookup: 1 0 0 "Between nt tn" { "Between nt tn"  } []
Lookup: 1 0 0 "Between nt nt" { "Between nt nt"  } []
Lookup: 264 0 0 "Line of Writing" { "Starts with a"  } [' RQD' ('DFLT' <'dflt' > 'latn' <'dflt' > ) ]
Lookup: 259 0 0 "Cursive Attachment" { "Join"  } ['curs' ('DFLT' <'dflt' > 'latn' <'dflt' > ) ]
Lookup: 257 0 0 "Position Before b" { "Position Before b"  } []
Lookup: 257 0 0 "Position Before b.cut" { "Position Before b.cut"  } []
Lookup: 257 0 0 "Position Before ch" { "Position Before ch"  } []
Lookup: 257 0 0 "Position Before d" { "Position Before d"  } []
Lookup: 257 0 0 "Position Before f" { "Position Before f"  } []
Lookup: 257 0 0 "Position Before g" { "Position Before g"  } []
Lookup: 257 0 0 "Position Before j" { "Position Before j"  } []
Lookup: 257 0 0 "Position Before k" { "Position Before k"  } []
Lookup: 257 0 0 "Position Before l" { "Position Before l"  } []
Lookup: 257 0 0 "Position Before m" { "Position Before m"  } []
Lookup: 257 0 0 "Position Before n" { "Position Before n"  } []
Lookup: 257 0 0 "Position Before ng" { "Position Before ng"  } []
Lookup: 257 0 0 "Position Before nk" { "Position Before nk"  } []
Lookup: 257 0 0 "Position Before p" { "Position Before p"  } []
Lookup: 257 0 0 "Position Before p.cut" { "Position Before p.cut"  } []
Lookup: 257 0 0 "Position Before r" { "Position Before r"  } []
Lookup: 257 0 0 "Position Before sh" { "Position Before sh"  } []
Lookup: 257 0 0 "Position Before t" { "Position Before t"  } []
Lookup: 257 0 0 "Position Before th" { "Position Before th"  } []
Lookup: 257 0 0 "Position Before v" { "Position Before v"  } []
MarkAttachClasses: 1
DEI: 91125
ChainSub2: class "Between k *" 12 12 12 1
  Class: 9 a e i o u
  Class: 15 k g k.cut g.cut
  Class: 15 r l r.cut l.cut
  Class: 3 n m
  Class: 3 t d
  Class: 22 p b p.cut b.cut s.left
  Class: 23 f v f.cut v.cut s.right
  Class: 7 sh ch j
  Class: 5 ng nk
  Class: 7 th.over
  Class: 8 th.under
  BClass: 9 a e i o u
  BClass: 15 k g k.cut g.cut
  BClass: 15 r l r.cut l.cut
  BClass: 3 n m
  BClass: 3 t d
  BClass: 22 p b p.cut b.cut s.left
  BClass: 23 f v f.cut v.cut s.right
  BClass: 7 sh ch j
  BClass: 5 ng nk
  BClass: 7 th.over
  BClass: 8 th.under
  FClass: 9 a e i o u
  FClass: 15 k g k.cut g.cut
  FClass: 15 r l r.cut l.cut
  FClass: 3 n m
  FClass: 3 t d
  FClass: 22 p b p.cut b.cut s.left
  FClass: 23 f v f.cut v.cut s.right
  FClass: 7 sh ch j
  FClass: 5 ng nk
  FClass: 7 th.over
  FClass: 8 th.under
 1 0 0
  ClsList: 0
  BClsList:
  FClsList:
 0
  ClassNames: "0" "vowel" "k" "r" "n" "t" "p" "f" "ch" "ng" "tn" "nt"
  BClassNames: "0" "vowel" "k" "r" "n" "t" "p" "f" "ch" "ng" "tn" "nt"
  FClassNames: "0" "vowel" "k" "r" "n" "t" "p" "f" "ch" "ng" "tn" "nt"
EndFPST
ChainSub2: class "Between r *" 12 12 12 1
  Class: 9 a e i o u
  Class: 15 k g k.cut g.cut
  Class: 15 r l r.cut l.cut
  Class: 3 n m
  Class: 3 t d
  Class: 22 p b p.cut b.cut s.left
  Class: 23 f v f.cut v.cut s.right
  Class: 7 sh ch j
  Class: 5 ng nk
  Class: 7 th.over
  Class: 8 th.under
  BClass: 9 a e i o u
  BClass: 15 k g k.cut g.cut
  BClass: 15 r l r.cut l.cut
  BClass: 3 n m
  BClass: 3 t d
  BClass: 22 p b p.cut b.cut s.left
  BClass: 23 f v f.cut v.cut s.right
  BClass: 7 sh ch j
  BClass: 5 ng nk
  BClass: 7 th.over
  BClass: 8 th.under
  FClass: 9 a e i o u
  FClass: 15 k g k.cut g.cut
  FClass: 15 r l r.cut l.cut
  FClass: 3 n m
  FClass: 3 t d
  FClass: 22 p b p.cut b.cut s.left
  FClass: 23 f v f.cut v.cut s.right
  FClass: 7 sh ch j
  FClass: 5 ng nk
  FClass: 7 th.over
  FClass: 8 th.under
 1 0 0
  ClsList: 0
  BClsList:
  FClsList:
 0
  ClassNames: "0" "vowel" "k" "r" "n" "t" "p" "f" "ch" "ng" "tn" "nt"
  BClassNames: "0" "vowel" "k" "r" "n" "t" "p" "f" "ch" "ng" "tn" "nt"
  FClassNames: "0" "vowel" "k" "r" "n" "t" "p" "f" "ch" "ng" "tn" "nt"
EndFPST
ChainSub2: class "Between n *" 12 12 12 1
  Class: 9 a e i o u
  Class: 15 k g k.cut g.cut
  Class: 15 r l r.cut l.cut
  Class: 3 n m
  Class: 3 t d
  Class: 22 p b p.cut b.cut s.left
  Class: 23 f v f.cut v.cut s.right
  Class: 7 sh ch j
  Class: 5 ng nk
  Class: 7 th.over
  Class: 8 th.under
  BClass: 9 a e i o u
  BClass: 15 k g k.cut g.cut
  BClass: 15 r l r.cut l.cut
  BClass: 3 n m
  BClass: 3 t d
  BClass: 22 p b p.cut b.cut s.left
  BClass: 23 f v f.cut v.cut s.right
  BClass: 7 sh ch j
  BClass: 5 ng nk
  BClass: 7 th.over
  BClass: 8 th.under
  FClass: 9 a e i o u
  FClass: 15 k g k.cut g.cut
  FClass: 15 r l r.cut l.cut
  FClass: 3 n m
  FClass: 3 t d
  FClass: 22 p b p.cut b.cut s.left
  FClass: 23 f v f.cut v.cut s.right
  FClass: 7 sh ch j
  FClass: 5 ng nk
  FClass: 7 th.over
  FClass: 8 th.under
 1 0 0
  ClsList: 0
  BClsList:
  FClsList:
 0
  ClassNames: "0" "vowel" "k" "r" "n" "t" "p" "f" "ch" "ng" "tn" "nt"
  BClassNames: "0" "vowel" "k" "r" "n" "t" "p" "f" "ch" "ng" "tn" "nt"
  FClassNames: "0" "vowel" "k" "r" "n" "t" "p" "f" "ch" "ng" "tn" "nt"
EndFPST
ChainSub2: class "Between t *" 12 12 12 1
  Class: 9 a e i o u
  Class: 15 k g k.cut g.cut
  Class: 15 r l r.cut l.cut
  Class: 3 n m
  Class: 3 t d
  Class: 22 p b p.cut b.cut s.left
  Class: 23 f v f.cut v.cut s.right
  Class: 7 sh ch j
  Class: 5 ng nk
  Class: 7 th.over
  Class: 8 th.under
  BClass: 9 a e i o u
  BClass: 15 k g k.cut g.cut
  BClass: 15 r l r.cut l.cut
  BClass: 3 n m
  BClass: 3 t d
  BClass: 22 p b p.cut b.cut s.left
  BClass: 23 f v f.cut v.cut s.right
  BClass: 7 sh ch j
  BClass: 5 ng nk
  BClass: 7 th.over
  BClass: 8 th.under
  FClass: 9 a e i o u
  FClass: 15 k g k.cut g.cut
  FClass: 15 r l r.cut l.cut
  FClass: 3 n m
  FClass: 3 t d
  FClass: 22 p b p.cut b.cut s.left
  FClass: 23 f v f.cut v.cut s.right
  FClass: 7 sh ch j
  FClass: 5 ng nk
  FClass: 7 th.over
  FClass: 8 th.under
 1 0 0
  ClsList: 0
  BClsList:
  FClsList:
 0
  ClassNames: "0" "vowel" "k" "r" "n" "t" "p" "f" "ch" "ng" "tn" "nt"
  BClassNames: "0" "vowel" "k" "r" "n" "t" "p" "f" "ch" "ng" "tn" "nt"
  FClassNames: "0" "vowel" "k" "r" "n" "t" "p" "f" "ch" "ng" "tn" "nt"
EndFPST
ChainSub2: class "Between p *" 12 12 12 1
  Class: 9 a e i o u
  Class: 15 k g k.cut g.cut
  Class: 15 r l r.cut l.cut
  Class: 3 n m
  Class: 3 t d
  Class: 22 p b p.cut b.cut s.left
  Class: 23 f v f.cut v.cut s.right
  Class: 7 sh ch j
  Class: 5 ng nk
  Class: 7 th.over
  Class: 8 th.under
  BClass: 9 a e i o u
  BClass: 15 k g k.cut g.cut
  BClass: 15 r l r.cut l.cut
  BClass: 3 n m
  BClass: 3 t d
  BClass: 22 p b p.cut b.cut s.left
  BClass: 23 f v f.cut v.cut s.right
  BClass: 7 sh ch j
  BClass: 5 ng nk
  BClass: 7 th.over
  BClass: 8 th.under
  FClass: 9 a e i o u
  FClass: 15 k g k.cut g.cut
  FClass: 15 r l r.cut l.cut
  FClass: 3 n m
  FClass: 3 t d
  FClass: 22 p b p.cut b.cut s.left
  FClass: 23 f v f.cut v.cut s.right
  FClass: 7 sh ch j
  FClass: 5 ng nk
  FClass: 7 th.over
  FClass: 8 th.under
 1 0 0
  ClsList: 0
  BClsList:
  FClsList:
 0
  ClassNames: "0" "vowel" "k" "r" "n" "t" "p" "f" "ch" "ng" "tn" "nt"
  BClassNames: "0" "vowel" "k" "r" "n" "t" "p" "f" "ch" "ng" "tn" "nt"
  FClassNames: "0" "vowel" "k" "r" "n" "t" "p" "f" "ch" "ng" "tn" "nt"
EndFPST
ChainSub2: class "Between f *" 12 12 12 1
  Class: 9 a e i o u
  Class: 15 k g k.cut g.cut
  Class: 15 r l r.cut l.cut
  Class: 3 n m
  Class: 3 t d
  Class: 22 p b p.cut b.cut s.left
  Class: 23 f v f.cut v.cut s.right
  Class: 7 sh ch j
  Class: 5 ng nk
  Class: 7 th.over
  Class: 8 th.under
  BClass: 9 a e i o u
  BClass: 15 k g k.cut g.cut
  BClass: 15 r l r.cut l.cut
  BClass: 3 n m
  BClass: 3 t d
  BClass: 22 p b p.cut b.cut s.left
  BClass: 23 f v f.cut v.cut s.right
  BClass: 7 sh ch j
  BClass: 5 ng nk
  BClass: 7 th.over
  BClass: 8 th.under
  FClass: 9 a e i o u
  FClass: 15 k g k.cut g.cut
  FClass: 15 r l r.cut l.cut
  FClass: 3 n m
  FClass: 3 t d
  FClass: 22 p b p.cut b.cut s.left
  FClass: 23 f v f.cut v.cut s.right
  FClass: 7 sh ch j
  FClass: 5 ng nk
  FClass: 7 th.over
  FClass: 8 th.under
 1 0 0
  ClsList: 0
  BClsList:
  FClsList:
 0
  ClassNames: "0" "vowel" "k" "r" "n" "t" "p" "f" "ch" "ng" "tn" "nt"
  BClassNames: "0" "vowel" "k" "r" "n" "t" "p" "f" "ch" "ng" "tn" "nt"
  FClassNames: "0" "vowel" "k" "r" "n" "t" "p" "f" "ch" "ng" "tn" "nt"
EndFPST
ChainSub2: class "Between ch *" 12 12 12 1
  Class: 9 a e i o u
  Class: 15 k g k.cut g.cut
  Class: 15 r l r.cut l.cut
  Class: 3 n m
  Class: 3 t d
  Class: 22 p b p.cut b.cut s.left
  Class: 23 f v f.cut v.cut s.right
  Class: 7 sh ch j
  Class: 5 ng nk
  Class: 7 th.over
  Class: 8 th.under
  BClass: 9 a e i o u
  BClass: 15 k g k.cut g.cut
  BClass: 15 r l r.cut l.cut
  BClass: 3 n m
  BClass: 3 t d
  BClass: 22 p b p.cut b.cut s.left
  BClass: 23 f v f.cut v.cut s.right
  BClass: 7 sh ch j
  BClass: 5 ng nk
  BClass: 7 th.over
  BClass: 8 th.under
  FClass: 9 a e i o u
  FClass: 15 k g k.cut g.cut
  FClass: 15 r l r.cut l.cut
  FClass: 3 n m
  FClass: 3 t d
  FClass: 22 p b p.cut b.cut s.left
  FClass: 23 f v f.cut v.cut s.right
  FClass: 7 sh ch j
  FClass: 5 ng nk
  FClass: 7 th.over
  FClass: 8 th.under
 1 0 0
  ClsList: 0
  BClsList:
  FClsList:
 0
  ClassNames: "0" "vowel" "k" "r" "n" "t" "p" "f" "ch" "ng" "tn" "nt"
  BClassNames: "0" "vowel" "k" "r" "n" "t" "p" "f" "ch" "ng" "tn" "nt"
  FClassNames: "0" "vowel" "k" "r" "n" "t" "p" "f" "ch" "ng" "tn" "nt"
EndFPST
ChainSub2: class "Between ng *" 12 12 12 1
  Class: 9 a e i o u
  Class: 15 k g k.cut g.cut
  Class: 15 r l r.cut l.cut
  Class: 3 n m
  Class: 3 t d
  Class: 22 p b p.cut b.cut s.left
  Class: 23 f v f.cut v.cut s.right
  Class: 7 sh ch j
  Class: 5 ng nk
  Class: 7 th.over
  Class: 8 th.under
  BClass: 9 a e i o u
  BClass: 15 k g k.cut g.cut
  BClass: 15 r l r.cut l.cut
  BClass: 3 n m
  BClass: 3 t d
  BClass: 22 p b p.cut b.cut s.left
  BClass: 23 f v f.cut v.cut s.right
  BClass: 7 sh ch j
  BClass: 5 ng nk
  BClass: 7 th.over
  BClass: 8 th.under
  FClass: 9 a e i o u
  FClass: 15 k g k.cut g.cut
  FClass: 15 r l r.cut l.cut
  FClass: 3 n m
  FClass: 3 t d
  FClass: 22 p b p.cut b.cut s.left
  FClass: 23 f v f.cut v.cut s.right
  FClass: 7 sh ch j
  FClass: 5 ng nk
  FClass: 7 th.over
  FClass: 8 th.under
 1 0 0
  ClsList: 0
  BClsList:
  FClsList:
 0
  ClassNames: "0" "vowel" "k" "r" "n" "t" "p" "f" "ch" "ng" "tn" "nt"
  BClassNames: "0" "vowel" "k" "r" "n" "t" "p" "f" "ch" "ng" "tn" "nt"
  FClassNames: "0" "vowel" "k" "r" "n" "t" "p" "f" "ch" "ng" "tn" "nt"
EndFPST
ChainSub2: class "Between tn *" 12 12 12 1
  Class: 9 a e i o u
  Class: 15 k g k.cut g.cut
  Class: 15 r l r.cut l.cut
  Class: 3 n m
  Class: 3 t d
  Class: 22 p b p.cut b.cut s.left
  Class: 23 f v f.cut v.cut s.right
  Class: 7 sh ch j
  Class: 5 ng nk
  Class: 7 th.over
  Class: 8 th.under
  BClass: 9 a e i o u
  BClass: 15 k g k.cut g.cut
  BClass: 15 r l r.cut l.cut
  BClass: 3 n m
  BClass: 3 t d
  BClass: 22 p b p.cut b.cut s.left
  BClass: 23 f v f.cut v.cut s.right
  BClass: 7 sh ch j
  BClass: 5 ng nk
  BClass: 7 th.over
  BClass: 8 th.under
  FClass: 9 a e i o u
  FClass: 15 k g k.cut g.cut
  FClass: 15 r l r.cut l.cut
  FClass: 3 n m
  FClass: 3 t d
  FClass: 22 p b p.cut b.cut s.left
  FClass: 23 f v f.cut v.cut s.right
  FClass: 7 sh ch j
  FClass: 5 ng nk
  FClass: 7 th.over
  FClass: 8 th.under
 1 0 0
  ClsList: 0
  BClsList:
  FClsList:
 0
  ClassNames: "0" "vowel" "k" "r" "n" "t" "p" "f" "ch" "ng" "tn" "nt"
  BClassNames: "0" "vowel" "k" "r" "n" "t" "p" "f" "ch" "ng" "tn" "nt"
  FClassNames: "0" "vowel" "k" "r" "n" "t" "p" "f" "ch" "ng" "tn" "nt"
EndFPST
ChainSub2: class "Between nt *" 12 12 12 1
  Class: 9 a e i o u
  Class: 15 k g k.cut g.cut
  Class: 15 r l r.cut l.cut
  Class: 3 n m
  Class: 3 t d
  Class: 22 p b p.cut b.cut s.left
  Class: 23 f v f.cut v.cut s.right
  Class: 7 sh ch j
  Class: 5 ng nk
  Class: 7 th.over
  Class: 8 th.under
  BClass: 9 a e i o u
  BClass: 15 k g k.cut g.cut
  BClass: 15 r l r.cut l.cut
  BClass: 3 n m
  BClass: 3 t d
  BClass: 22 p b p.cut b.cut s.left
  BClass: 23 f v f.cut v.cut s.right
  BClass: 7 sh ch j
  BClass: 5 ng nk
  BClass: 7 th.over
  BClass: 8 th.under
  FClass: 9 a e i o u
  FClass: 15 k g k.cut g.cut
  FClass: 15 r l r.cut l.cut
  FClass: 3 n m
  FClass: 3 t d
  FClass: 22 p b p.cut b.cut s.left
  FClass: 23 f v f.cut v.cut s.right
  FClass: 7 sh ch j
  FClass: 5 ng nk
  FClass: 7 th.over
  FClass: 8 th.under
 1 0 0
  ClsList: 0
  BClsList:
  FClsList:
 0
  ClassNames: "0" "vowel" "k" "r" "n" "t" "p" "f" "ch" "ng" "tn" "nt"
  BClassNames: "0" "vowel" "k" "r" "n" "t" "p" "f" "ch" "ng" "tn" "nt"
  FClassNames: "0" "vowel" "k" "r" "n" "t" "p" "f" "ch" "ng" "tn" "nt"
EndFPST
ChainSub2: class "th Direction" 5 5 5 7
  Class: 2 th
  Class: 3 r l
  Class: 1 o
  Class: 3 a e
  BClass: 2 th
  BClass: 3 r l
  BClass: 1 o
  BClass: 3 a e
  FClass: 2 th
  FClass: 3 r l
  FClass: 1 o
  FClass: 3 a e
 1 0 1
  ClsList: 1
  BClsList:
  FClsList: 2
 1
  SeqLookup: 0 "Under th"
 1 0 1
  ClsList: 1
  BClsList:
  FClsList: 3
 1
  SeqLookup: 0 "Under th"
 1 1 0
  ClsList: 1
  BClsList: 2
  FClsList:
 1
  SeqLookup: 0 "Under th"
 1 1 0
  ClsList: 1
  BClsList: 3
  FClsList:
 1
  SeqLookup: 0 "Under th"
 1 0 2
  ClsList: 1
  BClsList:
  FClsList: 4 2
 1
  SeqLookup: 0 "Under th"
 1 2 0
  ClsList: 1
  BClsList: 4 2
  FClsList:
 1
  SeqLookup: 0 "Under th"
 1 0 0
  ClsList: 1
  BClsList:
  FClsList:
 1
  SeqLookup: 0 "Over th"
  ClassNames: "All_Others" "th" "r" "o" "circle"
  BClassNames: "All_Others" "th" "r" "o" "circle"
  FClassNames: "All_Others" "th" "r" "o" "circle"
EndFPST
ChainSub2: class "s Direction" 8 8 8 15
  Class: 1 s
  Class: 23 k g f v sh ch j s.right
  Class: 14 r l p b s.left
  Class: 3 a e
  Class: 15 n m t d ng nk o
  Class: 1 u
  Class: 1 i
  BClass: 1 s
  BClass: 23 k g f v sh ch j s.right
  BClass: 14 r l p b s.left
  BClass: 3 a e
  BClass: 15 n m t d ng nk o
  BClass: 1 u
  BClass: 1 i
  FClass: 1 s
  FClass: 23 k g f v sh ch j s.right
  FClass: 14 r l p b s.left
  FClass: 3 a e
  FClass: 15 n m t d ng nk o
  FClass: 1 u
  FClass: 1 i
 1 2 0
  ClsList: 1
  BClsList: 4 2
  FClsList:
 1
  SeqLookup: 0 "Right s"
 1 2 0
  ClsList: 1
  BClsList: 4 3
  FClsList:
 1
  SeqLookup: 0 "Left s"
 1 2 0
  ClsList: 1
  BClsList: 4 5
  FClsList:
 1
  SeqLookup: 0 "Left s"
 1 2 0
  ClsList: 1
  BClsList: 7 2
  FClsList:
 1
  SeqLookup: 0 "Right s"
 1 2 0
  ClsList: 1
  BClsList: 7 3
  FClsList:
 1
  SeqLookup: 0 "Left s"
 1 2 0
  ClsList: 1
  BClsList: 7 5
  FClsList:
 1
  SeqLookup: 0 "Left s"
 1 1 0
  ClsList: 1
  BClsList: 2
  FClsList:
 1
  SeqLookup: 0 "Right s"
 1 1 0
  ClsList: 1
  BClsList: 3
  FClsList:
 1
  SeqLookup: 0 "Left s"
 1 1 0
  ClsList: 1
  BClsList: 5
  FClsList:
 1
  SeqLookup: 0 "Left s"
 1 2 0
  ClsList: 1
  BClsList: 7 6
  FClsList:
 1
  SeqLookup: 0 "Right s"
 1 1 0
  ClsList: 1
  BClsList: 7
  FClsList:
 1
  SeqLookup: 0 "Left s"
 1 0 2
  ClsList: 1
  BClsList:
  FClsList: 4 3
 1
  SeqLookup: 0 "Left s"
 1 0 2
  ClsList: 1
  BClsList:
  FClsList: 7 3
 1
  SeqLookup: 0 "Left s"
 1 0 1
  ClsList: 1
  BClsList:
  FClsList: 3
 1
  SeqLookup: 0 "Left s"
 1 0 0
  ClsList: 1
  BClsList:
  FClsList:
 1
  SeqLookup: 0 "Right s"
  ClassNames: "All_Others" "s" "right" "left" "circle" "sharp" "u" "i"
  BClassNames: "All_Others" "s" "right" "left" "circle" "sharp" "u" "i"
  FClassNames: "All_Others" "s" "right" "left" "circle" "sharp" "u" "i"
EndFPST
ChainSub2: class "p Joinings" 3 3 3 1
  Class: 3 p b
  Class: 3 r l
  BClass: 3 p b
  BClass: 3 r l
  FClass: 3 p b
  FClass: 3 r l
 1 0 1
  ClsList: 1
  BClsList:
  FClsList: 2
 1
  SeqLookup: 0 "Cut Consonant"
  ClassNames: "All_Others" "p" "r"
  BClassNames: "All_Others" "p" "r"
  FClassNames: "All_Others" "p" "r"
EndFPST
ChainSub2: glyph "Vowel After Overrides" 0 0 0 3
 String: 1 a
 BString: 1 b
 FString: 0 
 1
  SeqLookup: 0 "After b"
 String: 1 a
 BString: 7 s.right
 FString: 0 
 1
  SeqLookup: 0 "After s.right"
 String: 1 a
 BString: 6 s.left
 FString: 0 
 1
  SeqLookup: 0 "After s.left"
EndFPST
ChainSub2: class "Vowel After" 12 12 12 10
  Class: 1 a
  Class: 7 sh ch j
  Class: 23 f v f.cut v.cut s.right
  Class: 3 k g
  Class: 3 n m
  Class: 10 p b s.left
  Class: 15 r l r.cut l.cut
  Class: 3 t d
  Class: 7 th.over
  Class: 8 th.under
  Class: 5 ng nk
  BClass: 1 a
  BClass: 7 sh ch j
  BClass: 23 f v f.cut v.cut s.right
  BClass: 3 k g
  BClass: 3 n m
  BClass: 10 p b s.left
  BClass: 15 r l r.cut l.cut
  BClass: 3 t d
  BClass: 7 th.over
  BClass: 8 th.under
  BClass: 5 ng nk
  FClass: 1 a
  FClass: 7 sh ch j
  FClass: 23 f v f.cut v.cut s.right
  FClass: 3 k g
  FClass: 3 n m
  FClass: 10 p b s.left
  FClass: 15 r l r.cut l.cut
  FClass: 3 t d
  FClass: 7 th.over
  FClass: 8 th.under
  FClass: 5 ng nk
 1 1 0
  ClsList: 1
  BClsList: 2
  FClsList:
 1
  SeqLookup: 0 "After ch"
 1 1 0
  ClsList: 1
  BClsList: 3
  FClsList:
 1
  SeqLookup: 0 "After f"
 1 1 0
  ClsList: 1
  BClsList: 4
  FClsList:
 1
  SeqLookup: 0 "After k"
 1 1 0
  ClsList: 1
  BClsList: 5
  FClsList:
 1
  SeqLookup: 0 "After n"
 1 1 0
  ClsList: 1
  BClsList: 6
  FClsList:
 1
  SeqLookup: 0 "After p"
 1 1 0
  ClsList: 1
  BClsList: 7
  FClsList:
 1
  SeqLookup: 0 "After r"
 1 1 0
  ClsList: 1
  BClsList: 8
  FClsList:
 1
  SeqLookup: 0 "After t"
 1 1 0
  ClsList: 1
  BClsList: 9
  FClsList:
 1
  SeqLookup: 0 "After tn"
 1 1 0
  ClsList: 1
  BClsList: 10
  FClsList:
 1
  SeqLookup: 0 "After nt"
 1 1 0
  ClsList: 1
  BClsList: 11
  FClsList:
 1
  SeqLookup: 0 "After ng"
  ClassNames: "All_Others" "a" "ch" "f" "k" "n" "p" "r" "t" "tn" "nt" "ng"
  BClassNames: "All_Others" "a" "ch" "f" "k" "n" "p" "r" "t" "tn" "nt" "ng"
  FClassNames: "All_Others" "a" "ch" "f" "k" "n" "p" "r" "t" "tn" "nt" "ng"
EndFPST
ChainPos2: class "Starts with a" 7 7 12 11
  Class: 5 a.ach
  Class: 4 a.af
  Class: 5 a.ang
  Class: 4 a.ap
  Class: 4 a.at
  Class: 4 a.av
  BClass: 5 a.ach
  BClass: 4 a.af
  BClass: 5 a.ang
  BClass: 4 a.ap
  BClass: 4 a.at
  BClass: 4 a.av
  FClass: 2 b 
  FClass: 5 b.cut
  FClass: 2 ch
  FClass: 1 f
  FClass: 1 j
  FClass: 2 ng
  FClass: 2 nk
  FClass: 2 p 
  FClass: 5 p.cut
  FClass: 2 sh
  FClass: 1 v
 1 0 1
  ClsList: 4
  BClsList:
  FClsList: 1
 1
  SeqLookup: 0 "Position Before b"
 1 0 1
  ClsList: 4
  BClsList:
  FClsList: 2
 1
  SeqLookup: 0 "Position Before b.cut"
 1 0 1
  ClsList: 1
  BClsList:
  FClsList: 3
 1
  SeqLookup: 0 "Position Before ch"
 1 0 1
  ClsList: 2
  BClsList:
  FClsList: 4
 1
  SeqLookup: 0 "Position Before f"
 1 0 1
  ClsList: 1
  BClsList:
  FClsList: 5
 1
  SeqLookup: 0 "Position Before j"
 1 0 1
  ClsList: 3
  BClsList:
  FClsList: 6
 1
  SeqLookup: 0 "Position Before ng"
 1 0 1
  ClsList: 3
  BClsList:
  FClsList: 7
 1
  SeqLookup: 0 "Position Before nk"
 1 0 1
  ClsList: 4
  BClsList:
  FClsList: 8
 1
  SeqLookup: 0 "Position Before p"
 1 0 1
  ClsList: 4
  BClsList:
  FClsList: 9
 1
  SeqLookup: 0 "Position Before p.cut"
 1 0 1
  ClsList: 1
  BClsList:
  FClsList: 10
 1
  SeqLookup: 0 "Position Before sh"
 1 0 1
  ClsList: 6
  BClsList:
  FClsList: 11
 1
  SeqLookup: 0 "Position Before v"
  ClassNames: "All_Others" "a.ach" "a.af" "a.ang" "a.ap" "a.at" "a.av"
  BClassNames: "All_Others" "a.ach" "a.af" "a.ang" "a.ap" "a.at" "a.av"
  FClassNames: "All_Others" "b" "b.cut" "ch" "f" "j" "ng" "nk" "p" "p.cut" "sh" "v"
EndFPST
ChainSub2: glyph "Vowel Before Overrides" 0 0 0 3
 String: 1 a
 BString: 0 
 FString: 1 l
 1
  SeqLookup: 0 "Before l"
 String: 1 a
 BString: 0 
 FString: 1 v
 1
  SeqLookup: 0 "Before v"
 String: 1 a
 BString: 0 
 FString: 7 s.right
 1
  SeqLookup: 0 "Before s.right"
EndFPST
ChainSub2: class "Vowel Before" 12 1 12 10
  Class: 1 a
  Class: 7 sh ch j
  Class: 11 f v s.right
  Class: 15 k g k.cut g.cut
  Class: 3 n m
  Class: 22 p b p.cut b.cut s.left
  Class: 3 r l
  Class: 3 t d
  Class: 7 th.over
  Class: 8 th.under
  Class: 5 ng nk
  FClass: 1 a
  FClass: 7 sh ch j
  FClass: 11 f v s.right
  FClass: 15 k g k.cut g.cut
  FClass: 3 n m
  FClass: 22 p b p.cut b.cut s.left
  FClass: 3 r l
  FClass: 3 t d
  FClass: 7 th.over
  FClass: 8 th.under
  FClass: 5 ng nk
 1 0 1
  ClsList: 1
  BClsList:
  FClsList: 2
 1
  SeqLookup: 0 "Before ch"
 1 0 1
  ClsList: 1
  BClsList:
  FClsList: 3
 1
  SeqLookup: 0 "Before f"
 1 0 1
  ClsList: 1
  BClsList:
  FClsList: 4
 1
  SeqLookup: 0 "Before k"
 1 0 1
  ClsList: 1
  BClsList:
  FClsList: 5
 1
  SeqLookup: 0 "Before n"
 1 0 1
  ClsList: 1
  BClsList:
  FClsList: 6
 1
  SeqLookup: 0 "Before p"
 1 0 1
  ClsList: 1
  BClsList:
  FClsList: 7
 1
  SeqLookup: 0 "Before r"
 1 0 1
  ClsList: 1
  BClsList:
  FClsList: 8
 1
  SeqLookup: 0 "Before t"
 1 0 1
  ClsList: 1
  BClsList:
  FClsList: 9
 1
  SeqLookup: 0 "Before tn"
 1 0 1
  ClsList: 1
  BClsList:
  FClsList: 10
 1
  SeqLookup: 0 "Before nt"
 1 0 1
  ClsList: 1
  BClsList:
  FClsList: 11
 1
  SeqLookup: 0 "Before ng"
  ClassNames: "All_Others" "a" "ch" "f" "k" "n" "p" "r" "t" "tn" "nt" "ng"
  BClassNames: "All_Others"
  FClassNames: "All_Others" "a" "ch" "f" "k" "n" "p" "r" "t" "tn" "nt" "ng"
EndFPST
Encoding: ISO8859-1
UnicodeInterp: none
NameList: AGL For New Fonts
DisplaySize: -72
AntiAlias: 1
FitToEm: 0
WinInfo: 104 26 10
BeginPrivate: 0
EndPrivate
TeXData: 1 0 0 346030 173015 115343 0 1048576 115343 783286 444596 497025 792723 393216 433062 380633 303038 157286 324010 404750 52429 2506097 1059062 262144
AnchorClass2: "Join" "Join"
EndSplineFont
