SplineFontDB: 3.2
FontName: Grascii
FullName: Grascii
FamilyName: Grascii
Weight: Regular
Copyright: Copyright (c) 2025, Grascii: Language and Tools for Gregg Shorthand
UComments: "2025-5-9: Created with FontForge (http://fontforge.org)"
Version: 001.000
StrokeWidth: 10
ItalicAngle: 0
UnderlinePosition: -100
UnderlineWidth: 50
Ascent: 850
Descent: 150
InvalidEm: 0
LayerCount: 2
Layer: 0 0 "Back" 1
Layer: 1 0 "Fore" 0
StrokedFont: 1
XUID: [1021 822 1269808884 1022652]
FSType: 0
OS2Version: 0
OS2_WeightWidthSlopeOnly: 0
OS2_UseTypoMetrics: 1
CreationTime: 1746848514
ModificationTime: 1747517363
PfmFamily: 17
TTFWeight: 700
TTFWidth: 5
LineGap: 90
VLineGap: 0
OS2TypoAscent: 0
OS2TypoAOffset: 1
OS2TypoDescent: 0
OS2TypoDOffset: 1
OS2TypoLinegap: 90
OS2WinAscent: 0
OS2WinAOffset: 1
OS2WinDescent: 0
OS2WinDOffset: 1
HheadAscent: 0
HheadAOffset: 1
HheadDescent: 0
HheadDOffset: 1
OS2Vendor: 'PfEd'
Lookup: 4 0 0 "Multichar strokes" { "ch sh th ng nk"  } ['rlig' ('DFLT' <'dflt' > 'latn' <'dflt' > ) ]
Lookup: 6 0 0 "Vowel Joinings" { "Vowel Before Overrides"  "Vowel Before"  } ['rclt' ('DFLT' <'dflt' > 'latn' <'dflt' > ) ]
Lookup: 1 0 0 "Before ch" { "Before ch"  } []
Lookup: 1 0 0 "Before f" { "Before f"  } []
Lookup: 1 0 0 "Before k" { "Before k"  } []
Lookup: 1 0 0 "Before l" { "Before l"  } []
Lookup: 1 0 0 "Before ng" { "Before ng"  } []
Lookup: 1 0 0 "Before n" { "Before n"  } []
Lookup: 1 0 0 "Before p" { "Before p"  } []
Lookup: 1 0 0 "Before r" { "Before r"  } []
Lookup: 1 0 0 "Before th" { "Before th"  } []
Lookup: 1 0 0 "Before t" { "Before t"  } []
Lookup: 1 0 0 "Before v" { "Before v"  } []
Lookup: 259 0 0 "Cursive Attachment" { "Join"  } ['curs' ('DFLT' <'dflt' > 'latn' <'dflt' > ) ]
MarkAttachClasses: 1
DEI: 91125
ChainSub2: glyph "Vowel Before Overrides" 0 0 0 2
 String: 1 a
 BString: 0
 FString: 1 l
 1
  SeqLookup: 0 "Before l"
 String: 1 a
 BString: 0
 FString: 1 v
 1
  SeqLookup: 0 "Before v"
EndFPST
ChainSub2: class "Vowel Before" 11 1 11 9
  Class: 1 a
  Class: 7 sh ch j
  Class: 3 f v
  Class: 3 k g
  Class: 3 n m
  Class: 3 p b
  Class: 3 r l
  Class: 3 t d
  Class: 2 th
  Class: 5 ng nk
  FClass: 1 a
  FClass: 7 sh ch j
  FClass: 3 f v
  FClass: 3 k g
  FClass: 3 n m
  FClass: 3 p b
  FClass: 3 r l
  FClass: 3 t d
  FClass: 2 th
  FClass: 5 ng nk
 1 0 1
  ClsList: 1
  BClsList:
  FClsList: 2
 1
  SeqLookup: 0 "Before ch"
 1 0 1
  ClsList: 1
  BClsList:
  FClsList: 3
 1
  SeqLookup: 0 "Before f"
 1 0 1
  ClsList: 1
  BClsList:
  FClsList: 4
 1
  SeqLookup: 0 "Before k"
 1 0 1
  ClsList: 1
  BClsList:
  FClsList: 5
 1
  SeqLookup: 0 "Before n"
 1 0 1
  ClsList: 1
  BClsList:
  FClsList: 6
 1
  SeqLookup: 0 "Before p"
 1 0 1
  ClsList: 1
  BClsList:
  FClsList: 7
 1
  SeqLookup: 0 "Before r"
 1 0 1
  ClsList: 1
  BClsList:
  FClsList: 8
 1
  SeqLookup: 0 "Before t"
 1 0 1
  ClsList: 1
  BClsList:
  FClsList: 9
 1
  SeqLookup: 0 "Before th"
 1 0 1
  ClsList: 1
  BClsList:
  FClsList: 10
 1
  SeqLookup: 0 "Before ng"
  ClassNames: "All_Others" "a" "ch" "f" "k" "n" "p" "r" "t" "th" "ng"
  BClassNames: "All_Others"
  FClassNames: "All_Others" "a" "ch" "f" "k" "n" "p" "r" "t" "th" "ng"
EndFPST
Encoding: ISO8859-1
UnicodeInterp: none
NameList: AGL For New Fonts
DisplaySize: -72
AntiAlias: 1
FitToEm: 0
WinInfo: 78 26 10
BeginPrivate: 0
EndPrivate
TeXData: 1 0 0 346030 173015 115343 0 1048576 115343 783286 444596 497025 792723 393216 433062 380633 303038 157286 324010 404750 52429 2506097 1059062 262144
AnchorClass2: "Join" "Join"
EndSplineFont
